project/abaut/urls.py
from . import views
from django.urls import path


app_name = "abaut"

urlpatterns = [
    path("", views.home, name="home"),

]

project/cliente/urls.py
from . import views
from django.urls import path


app_name = "cliente"

urlpatterns = [
    path("", views.home, name="home"),

]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
    path("abaut/", include("abaut.urls"))
    # path('saludar/', views.saludo),
    # path('otra-vista/', views.segunda_vista),
    # path('nombre/<nombre>/<apellido>', views.nombre),
    # path('probando_template/', views.probando_template),
    # path('notas/', views.mis_notas),
    # path('hora', views.fecha_hora),
    # path('persona/', views.persona)
]

project/core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),

]

project/producto/urls.py
from django.urls import path
from . import views


app_name = "producto"

urlpatterns = [
    path("", views.home, name="home"),
    path("productocategoria/create/", views.productocategoria_create,
         name="productocategoria_create"),
    path("instrumentoscuerdas/create/", views.instrumentos_de_cuerdas,
         name="instrumentos_de_cuerdas"),
    path("instrumentosaire/create/", views.instrumentos_de_aire,
         name="instrumentos_de_aire"),
    # path("productocategoria/create/", views.productocategoria_create,
    #      name="productocategoria_create"),
    # path("instrumentoscuerdas/create/", views.instrumentos_de_cuerdas,
    #      name="instrumentos_de_cuerdas"),
]

project/abaut/models.py
from django.db import models

# Create your models here.

project/cliente/models.py
from django.db import models

# Create your models here.


class Pais(models.Model):
    nombre = models.CharField(max_length=50, verbose_name="país")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "paises"


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)
    pais_origen_id = models.ForeignKey(
        Pais, on_delete=models.SET_NULL, null=True, verbose_name="país de origen")

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

project/core/models.py
from django.db import models

# Create your models here.

project/producto/models.py
from django.db import models

# Create your models here.


# class InstrumentosDeCuerdas(models.Model):
#     """Modelo de instrumentos de cuerdas"""
#     nombre = models.CharField(max_length=200, unique=True)
#     precio = models.DecimalField(max_digits=10, decimal_places=2)
#     descripcion = models.TextField(
#         max_length=250, null=True, blank=True, verbose_name="descripción")
#     categoria = models.ForeignKey(
#         'ProductoCategoria', on_delete=models.SET_NULL, null=True, blank=True)
#     imagen = models.ImageField(
#         upload_to='instrumentos_de_cuerdas/', null=True, blank=True)

#     def __str__(self):
#         """Representa una instancia del modelo como una cadena de texto"""
#         return self.nombre


# class ProductoCategoria(models.Model):
#     """Categoría de productos"""
#     nombre = models.CharField(max_length=200, unique=True)
#     descripcion = models.CharField(
#         max_length=250, null=True, blank=True, verbose_name="descripción")

#     def __str__(self):
#         """Representa una instancia del modelo como una cadena de texto"""
#         return self.nombre

#     class Meta:
#         """Verbose_name es el nombre con el que se representa en el panel de administración"""
#         verbose_name = "categoría de productos"
#         verbose_name_plural = "categorías de productos"

class InstrumentoAire(models.Model):
    descripcion = models.CharField(
        max_length=250, null=True, blank=True, verbose_name="descripción")

    def __str__(self):
        return self.descripcion


class InstrumentoCuerdas(models.Model):
    descripcion = models.CharField(
        max_length=250, null=True, blank=True, verbose_name="descripción")

    def __str__(self):
        return self.descripcion


class Instrumento(models.Model):
    nombre = models.CharField(max_length=200)
    instrumentocuerdas = models.ForeignKey(
        InstrumentoCuerdas, on_delete=models.SET_NULL, null=True, blank=True)
    instrumentoaire = models.ForeignKey(
        InstrumentoAire, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre

project/producto/forms.py
from django import forms
from . import models


class InstrumentosForm(forms.ModelForm):
    class Meta:
        model = models.Instrumento
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"})
        }


class InstrumentoAireForm(forms.ModelForm):
    class Meta:
        model = models.InstrumentoAire
        fields = "__all__"
        widgets = {
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        }


class InstrumentoCuerdasForm(forms.ModelForm):
    class Meta:
        model = models.InstrumentoCuerdas
        fields = "__all__"
        widgets = {
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        }

project/abaut/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, "abaut/index.html")

project/cliente/views.py
from django.shortcuts import render
from . import models

# Create your views here.


def home(request):
    consulta_clientes = models.Cliente.objects.all()
    context = {"clientes": consulta_clientes}
    return render(request, "cliente/index.html", context)

project/config/views.py
from django.http import HttpResponse
from django.template import Template, Context
from django.shortcuts import render


def saludo(request):
    return HttpResponse("¡Hola Django!")


def segunda_vista(request):
    return HttpResponse("<h1>Segunda vista</h1>")


def nombre(request, nombre: str, apellido: str):
    nombre = nombre.capitalize()
    apellido = apellido.capitalize()
    return HttpResponse(f"{apellido}, {nombre}")


def probando_template(request):
    mi_html = open("./templates/template1.html", encoding="UTF-8")
    mi_template = Template(mi_html.read())
    mi_html.close()
    mi_contexto = Context({"saludo": "¡Bienvenido!", "autor": "Coderhose"})
    mi_documento = mi_template.render(mi_contexto)
    return HttpResponse(mi_documento)


def mis_notas(request):
    lista_de_notas = [2, 3, 5, 6, 8, 9]
    contexto = {"notas": lista_de_notas}
    return render(request, "notas.html", contexto)


def fecha_hora(request):
    from datetime import datetime
    ahora = datetime.now()
    return HttpResponse(f"<h1> ⏲️ Fecha y hora: {ahora:%d/%m/%Y %H:%M%S.%f}</h1>")


def persona(request):
    formulario = {"persona": {"nombre: ": "Edgard", "edad: ": "37"}}
    return render(request, "persona.html", formulario)

project/core/views.py
from django.shortcuts import render
from . import models

# Create your views here.


def home(request):
    return render(request, "core/index.html")

project/producto/views.py
from django.shortcuts import render, redirect
from . import models, forms

# Create your views here.


def home(request):
    query = models.Instrumento.objects.all()
    context = {"productos": query}
    return render(request, "producto/index.html", context)


def productocategoria_create(request):
    if request.method == "POST":
        form = forms.InstrumentosForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("producto:home")

    else:  # request.method == "GET"
        form = forms.InstrumentosForm()
    return render(request, "producto/productocategoria_create.html", {"form": form})


def instrumentos_de_cuerdas(request):
    if request.method == "POST":
        form = forms.InstrumentoCuerdasForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("producto:home")

    else:  # request.method == "GET"
        form = forms.InstrumentoCuerdasForm()
    return render(request, "producto/instrumentos_de_cuerdas.html", {"form": form})


def instrumentos_de_aire(request):
    if request.method == "POST":
        form = forms.InstrumentoAireForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("producto:home")

    else:  # request.method == "GET"
        form = forms.InstrumentoAireForm()
    return render(request, "producto/instrumentos_de_aire.html", {"form": form})

project/abaut/templates/abaut/index.html
{% extends 'core/base.html' %}

{% block titulo %}
Acerca de Nosotros
{% endblock titulo %}

{% block contenido %}
<div class="col mb-3">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ abaut }}</h2>
            <p class="card-text text-black">Desde una edad temprana, la música ha sido más que un simple pasatiempo
                para
                mí; ha sido una compañera constante, una inspiración y una forma de expresión que trasciende el
                lenguaje. Mis primeros recuerdos están llenos de melodías y ritmos, tocando el piano en la sala de estar
                de mi casa, aprendiendo acordes en una vieja guitarra y explorando la percusión en cualquier superficie
                que pudiera emitir un sonido. Esta pasión me llevó a recorrer un camino musical a lo largo de mi vida,
                desde actuaciones en pequeñas agrupaciones hasta estudiar formalmente música en la universidad.</p>

            <p class="card-text text-black">Después de años de estudiar y comprender profundamente la música y sus
                intrincados mecanismos, decidí
                que era el momento de compartir mi amor y conocimiento de los instrumentos musicales con otros. Así
                nació "Melodías Eternas", una tienda dedicada no solo a la venta de instrumentos musicales, sino a
                fomentar una comunidad de músicos, tanto novatos como experimentados, que comparten una pasión común por
                la música.</p>

            <p class="card-text text-black">En "Melodías Eternas", cada instrumento que ofrecemos ha sido seleccionado
                cuidadosamente, asegurándonos
                de que cumpla con nuestros altos estándares de calidad, sonido y accesibilidad. Entiendo que cada músico
                es único, y por eso nuestro enfoque es personalizado. Ya sea que estés buscando tu primer ukelele, una
                guitarra para acompañar tus canciones, o un piano para conciertos, estamos aquí para ayudarte a
                encontrar el instrumento perfecto que resuene contigo y con tu música.</p>

            <p class="card-text text-black">Más allá de vender instrumentos, en "Melodías Eternas" nos esforzamos por
                ser un recurso para nuestra
                comunidad musical. Ofrecemos talleres, clases de música y sesiones de jamming abiertas para que nuestros
                clientes puedan aprender más y sumergirse en el mundo de la música. Creemos que comprar un instrumento
                es solo el primer paso en un viaje musical, y estamos comprometidos a apoyar a cada cliente en cada
                etapa de ese viaje.</p>

            <p class="card-text text-black">A través de "Melodías Eternas", quiero transmitir no solo mi pasión por la
                música, sino también mi
                creencia en el poder transformador de la música en nuestras vidas. La música tiene el poder de consolar,
                motivar y unir a las personas, y es esta filosofía la que impulsa cada aspecto de nuestra tienda. Al
                visitar "Melodías Eternas", no solo estás comprando un instrumento, estás entrando a una comunidad donde
                la música y la pasión florecen juntas.</p>
        </div>
    </div>
</div>
<a href="{% url 'core:home' %}">Ir a home</a>
{% endblock contenido %}

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block titulo %}
Cliente
{% endblock titulo %}

{% block contenido %}
<div class="row row-cols-1 row-cols-md-2">
    {% for cliente in clientes %}
    <div class="col mb-3">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">{{ cliente.nombre }} {{ cliente.apellido }}</h2>
                <p class="card-text text-muted">Nacimiento: {{ cliente.nacimiento }}</p>
                {% if cliente.pais_origen_id %}
                <p class="card-text">{{ cliente.pais_origen_id }}</p>
                {% else %}
                <p class="card-text">No registra país de origen.</p>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% block title %}
    Tienda Edgard
    {% endblock title %}
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
        rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>



<body>
    <!-- Responsive navbar-->
    {% include 'core/components/navbar.html' %}
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">

        <div class="row align-items-center my-5">
            <h1 class="pb-lg-3 text-white px-3 py-2 rounded" style="background-color: #ff0080">
                {% block titulo %}
                Tienda Edgard
                {% endblock titulo %}
            </h1>
        </div>

        {% block contenido %}
        {% endblock contenido %}
    </div>
    <!-- Footer -->
    {# {% include 'core/components/footer.html' %} #}
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'core/js/scripts.js' %}"></script>
</body>

</html>

project/core/templates/core/components/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más info</a></div>
    </div>
</div>

project/core/templates/core/components/footer.html
<!-- Footer-->
<footer class="align-content-md-end bg-black">
    <div class="container  align-content-end">
        <p class="m-0 text-center text-white small">Mi sitio de ventas</p>
    </div>
</footer>

project/core/templates/core/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container px-5">
        <a class="navbar-brand" href="#page-top">Tienda Edgard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'abaut:home' %}">Abaut</a>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cliente:home' %}">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'producto:home' %}">Productos</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/components/titulo1.html
<div class="row align-items-center my-5">
    <h1 class="pb-lg-3 text-white px-3 py-2 rounded" style="background-color: #ff0080">
        {{ titulo }}
    </h1>
</div>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
{% include 'core/components/titulo1.html' with titulo="Musica Que Alegra"%}
{% endblock titulo %}

{% block contenido %}



<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Productos</h1>
            <h2 class="masthead-subheading mb-0">Que te cambian la vida</h2>
            <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Aprenda mas...</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
<!-- Content section 1-->
<section id="scroll">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'core/img/01.webp' %}"
                        alt="..." /></div>
            </div>
            <div class="col-lg-7 order-lg-2">
                <div class="p-6">
                    {% include 'core/components/card.html' with titulo="Adrenalina" %}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 2-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'core/img/02.webp' %}"
                        alt="..." /></div>
            </div>
            <div class="col-lg-7 order-lg-2">
                <div class="p-6">
                    {% include 'core/components/card.html' with titulo=" Emoción" %} </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 3-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'core/img/03.webp' %}"
                        alt="..." /></div>
            </div>
            <div class="col-lg-7 order-lg-2">
                <div class="p-6">
                    {% include 'core/components/card.html' with titulo="Inspiración" %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock contenido %}

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block titulo %}
Productos De Musica
{% endblock titulo %}


{% block contenido %}
<div style="display: flex; justify-content: start; gap: 20px; align-items: center;">
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:productocategoria_create' %}" class="btn btn-primary">Crear Instrumento Musical</a>
    </div>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:instrumentos_de_cuerdas' %}" class="btn btn-primary">Crear categoría instrumentos de
            cuerdas</a>
    </div>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:instrumentos_de_aire' %}" class="btn btn-primary">Crear categoría instrumentos de
            aire</a>
    </div>
</div>

<div class="py-lg-4">
    <form action="{% url 'producto:home' %}" method="get">
        <input type="text" name="consulta" placeholder="Buscar...">
    </form>
</div>

<ul>
    {% for producto in productos %}
    <li>{{ producto }}</li>
    {% endfor %}
</ul>

{# <a href="{% url 'core:home' %}">Ir a home</a> #}


{% endblock contenido %}

project/producto/templates/producto/instrumentos_de_aire.html
{% extends 'core/base.html' %}

{% block titulo %}
Categoría Instrumentos De Aire: Creación
{% endblock titulo %}

{% block contenido %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
<button type="submit">
    <a href="{% url 'producto:home' %}" class="btn btn-primary">Ir a Productos</a>
</button>
{% endblock contenido %}

project/producto/templates/producto/instrumentos_de_cuerdas.html
{% extends 'core/base.html' %}

{% block titulo %}
Categoría Instrumentos De Acuerdas: Creación
{% endblock titulo %}

{% block contenido %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
<button type="submit">
    <a href="{% url 'producto:home' %}" class="btn btn-primary">Ir a Productos</a>
</button>
{% endblock contenido %}

project/producto/templates/producto/productocategoria_create.html
{% extends 'core/base.html' %}

{% block titulo %}
Categoria de producto: Creación
{% endblock titulo %}

{% block contenido %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock contenido %}

project/templates/notas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1> Estas son mis notas </h1>
    <div style="text-align: center;">
        {% for nota in notas %}
        {% if nota < 4 %} <p style="color:red"> NOTA MALA: {{ nota }}</p>
            {% else %}
            <p style="color:green"> NOTA BUENA: {{ nota }}</p>
            {% endif %}
            {% endfor %}
    </div>

</body>

</html>

project/templates/persona.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1> La persona es: </h1>
    <div style="text-align: center;">
        {% for clave, valor in persona.items %}
        <p>{{clave | upper}} {{valor | upper}}</p>

        {% endfor %}
    </div>
</body>

</html>

project/templates/template1.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Code</title>
</head>

<body>
    <h1>{{saludo}} </h1>
    <p>Esta es nuestra primera pagina</p>
    <p> {{autor}} </p>
</body>

</html>